import io
import typing

class Entry:
    def add(self, obj: typing.Hashable) -> None: ...
    def add_bytes(self, obj: bytes) -> None: ...
    def add_reader(self, src: io.Reader[bytes]) -> int: ...
    def fork(self) -> "Entry": ...
    def _digest(self) -> int: ...

class Sketch:
    @staticmethod
    def load(buf: bytes) -> "Sketch": ...
    @staticmethod
    def from_iter(iter: typing.Iterator[typing.Hashable]) -> "Sketch": ...
    def save(self) -> bytes: ...
    def add(self, obj: typing.Hashable) -> None: ...
    def add_reader(self, src: io.Reader[bytes]) -> int: ...
    def add_entry(self, entry: Entry) -> None: ...
    def cardinality(self) -> float: ...
    def union(self, other: "Sketch") -> None: ...
    def intersection(self, other: "Sketch") -> float: ...
    def similarity(self, other: "Sketch") -> float: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __len__(self) -> int: ...
    def __float__(self) -> float: ...
    def __iadd__(self, other) -> "Sketch": ...
    def __iand__(self, other: "Sketch") -> "Sketch": ...
    def __and__(self, other: "Sketch") -> "Sketch": ...
    def __lt__(self, other: "Sketch") -> bool: ...
    def __le__(self, other: "Sketch") -> bool: ...
    def __gt__(self, other: "Sketch") -> bool: ...
    def __ge__(self, other: "Sketch") -> bool: ...

def __version_info__() -> str: ...

__version__: str
__hyperminhash_version__: str
__profile__: str
