import typing
from typing_extensions import final

class _SupportsRead(typing.Protocol):
    def read(self, n: int, /) -> bytes: ...

__all__ = [
    "__version_info__",
    "Entry",
    "Sketch",
    "__version__",
    "__profile__",
    "__hyperminhash_version__",
]

@final
class Entry:
    def add(self, obj: typing.Hashable, /) -> None: ...
    def add_bytes(self, obj: bytes, /) -> None: ...
    def add_reader(self, src: _SupportsRead, /) -> int: ...
    def fork(self) -> "Entry": ...
    def _digest(self) -> int: ...

@final
class Sketch:
    @staticmethod
    def load(buf: bytes, /) -> "Sketch": ...
    @staticmethod
    def from_iter(src: typing.Iterator[typing.Hashable], /) -> "Sketch": ...
    def save(self) -> bytes: ...
    def add(self, obj: typing.Hashable, /) -> None: ...
    def add_reader(self, src: _SupportsRead, /) -> int: ...
    def add_entry(self, entry: Entry, /) -> None: ...
    def cardinality(self) -> float: ...
    def union(self, other: "Sketch", /) -> None: ...
    def intersection(self, other: "Sketch", /, *, fast: bool = False) -> float: ...
    def similarity(self, other: "Sketch", /, *, fast: bool = False) -> float: ...
    def intersection_many(
        self, others: typing.Iterable["Sketch"], /, *, fast: bool = False
    ) -> list[float]: ...
    def similarity_many(
        self, others: typing.Iterable["Sketch"], /, *, fast: bool = False
    ) -> list[float]: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __len__(self) -> int: ...
    def __float__(self) -> float: ...
    def __iadd__(self, value, /) -> "Sketch": ...
    def __ior__(self, value: "Sketch", /) -> "Sketch": ...
    def __or__(self, value: "Sketch", /) -> "Sketch": ...
    def __lt__(self, value: "Sketch", /) -> bool: ...
    def __le__(self, value: "Sketch", /) -> bool: ...
    def __gt__(self, value: "Sketch", /) -> bool: ...
    def __ge__(self, value: "Sketch", /) -> bool: ...

def __version_info__() -> str: ...

__version__: str
__hyperminhash_version__: str
__profile__: str
